[unstable]
bindeps = true

[target.i686-pc-windows-gnullvm]
rustflags = ["-C", "linker=.cargo/zigcc-win32"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "linker=.cargo/zigcc-linux-x64"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "linker=.cargo/zigcc-linux-arm64"]
