[unstable]
bindeps = true

[target.i686-pc-windows-gnullvm]
rustflags = ["-C", "linker=.cargo/zigcc-i686-pc-windows-gnullvm"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "linker=.cargo/zigcc-x86_64-unknown-linux-musl"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "linker=.cargo/zigcc-aarch64-unknown-linux-musl"]
